// Topics
export const REQUEST_TOPICS = 'REQUEST_TOPICS';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const ERROR_RECEIVE_TOPICS = 'ERROR_RECEIVE_TOPICS';

// Products
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const ERROR_RECEIVE_PRODUCTS = 'ERROR_RECEIVE_PRODUCTS';

// Cart
export const REQUEST_CART = 'REQUEST_CART';
export const RECEIVE_CART = 'RECEIVE_CART';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_FROM_CART';
export const MAKE_ORDER = 'MAKE_ORDER';
export const ERROR_MAKE_ORDER = 'ERROR_MAKE_ORDER';